"""Init

Revision ID: 7b03f3e0ad0e
Revises: 
Create Date: 2026-07-13 01:33:42.855083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b03f3e0ad0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hcp',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_hcp_last_name', 'hcp', ['last_name'], unique=False)
    op.create_table('product',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('therapeutic_area', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interaction',
    sa.Column('hcp_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcp.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interaction_date', 'interaction', ['interaction_date'], unique=False)
    op.create_index('ix_interaction_hcp_id', 'interaction', ['hcp_id'], unique=False)
    op.create_table('follow_up',
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('action_item', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_follow_up_interaction_id', 'follow_up', ['interaction_id'], unique=False)
    op.create_table('interaction_product',
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction_product')
    op.drop_index('ix_follow_up_interaction_id', table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index('ix_interaction_hcp_id', table_name='interaction')
    op.drop_index('ix_interaction_date', table_name='interaction')
    op.drop_table('interaction')
    op.drop_table('product')
    op.drop_index('ix_hcp_last_name', table_name='hcp')
    op.drop_table('hcp')
    # ### end Alembic commands ###
