"""Add new Log Interaction fields

Revision ID: f15c19ebb72d
Revises: 7b03f3e0ad0e
Create Date: 2026-07-14 12:18:28.515785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15c19ebb72d'
down_revision: Union[str, Sequence[str], None] = '7b03f3e0ad0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction', sa.Column('interaction_type', sa.String(), nullable=True))
    op.add_column('interaction', sa.Column('interaction_time', sa.String(), nullable=True))
    op.add_column('interaction', sa.Column('attendees', sa.String(), nullable=True))
    op.add_column('interaction', sa.Column('topics_discussed', sa.Text(), nullable=True))
    op.add_column('interaction', sa.Column('outcomes', sa.Text(), nullable=True))
    op.add_column('interaction', sa.Column('follow_ups_text', sa.Text(), nullable=True))
    op.drop_column('interaction', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('interaction', 'follow_ups_text')
    op.drop_column('interaction', 'outcomes')
    op.drop_column('interaction', 'topics_discussed')
    op.drop_column('interaction', 'attendees')
    op.drop_column('interaction', 'interaction_time')
    op.drop_column('interaction', 'interaction_type')
    # ### end Alembic commands ###
